### ISSUE TITLE
 Still interested to maintain it?

### ISSUE THREAD

**Issue by francois2metz** [ringtrail/analytics.js-integration-ringtrail#1]
Hi

i'm building https://bytics.io. I'm would be happy to add Ringtrail to the list of available integrations.

Is your integration up to date? It yes, I can add it quickly.

**Comment by kressaty** [comment]
No it's not, and actually you've pointed out I should make this private :-). Thanks for reaching out though!

**Comment by francois2metz** [comment]
ok ;).
